### ISSUE TITLE
Database strecture

### ISSUE THREAD

**Issue by 0zaki1** [felipecastrosales/virtual-store-manager#31]
Hello @felipecastrosales ,
I'm running this app but i still need the database strecture , can you share it?
Thank You for your amazing work

**Comment by felipecastrosales** [comment]
this is a management implementation of my repository https://github.com/felipecastrosales/virtual-store

admins
![image](https://user-images.githubusercontent.com/59374587/110241020-6b933f00-7f2d-11eb-8c4a-4b99cad5626f.png)

coupons
![image](https://user-images.githubusercontent.com/59374587/110241028-6fbf5c80-7f2d-11eb-8cb1-c7aa06f6653d.png)

home
![image](https://user-images.githubusercontent.com/59374587/110241030-74841080-7f2d-11eb-86d0-08c04a5dd4bc.png)

orders
![image](https://user-images.githubusercontent.com/59374587/110241041-8796e080-7f2d-11eb-8fb3-cbb8dc397b7e.png)
![image](https://user-images.githubusercontent.com/59374587/110241045-8e255800-7f2d-11eb-9dd2-48d430b5a598.png)
![image](https://user-images.githubusercontent.com/59374587/110241058-97162980-7f2d-11eb-9b78-10b140a0a32f.png)

places
![image](https://user-images.githubusercontent.com/59374587/110241070-a5fcdc00-7f2d-11eb-8f89-0041659c4ce1.png)

products
![image](https://user-images.githubusercontent.com/59374587/110241076-abf2bd00-7f2d-11eb-953d-f8399d95433a.png)

users
![image](https://user-images.githubusercontent.com/59374587/110241080-b1e89e00-7f2d-11eb-9f33-56d77eae5779.png)

I hope this helps you, good luck and good studies
